services:
  app:
    build: .
    volumes:
      - .:/app
      - sqlite_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:////app/data/database.sqlite
    command: python main.py

volumes:
  sqlite_data: